import { test, expect } from "../helpers/softTest.js";
import { PRODUCTION_QA_IDS, assertProductionQa } from "../helpers/productionQaRules.js";

const TITLES = {
  "QA-001": "Storefront deployed",
  "QA-002": "Buyer API deployed",
  "QA-003": "Marketplace-core deployed",
  "QA-004": "Admin deployed",
  "QA-005": "1CA Fulfill deployed",
  "QA-006": "Stripe keys",
  "QA-007": "GCS tax certs",
  "QA-008": "ODB ↔ 1CA secrets",
  "QA-009": "Buyer email deliverability",
  "QA-010": "Mobile push credentials",
  "QA-011": "ONECA admin notify",
  "QA-012": "Playwright smoke (optional)",
  "QA-013": "Unit smoke (optional)",
  "QA-014": "Guest checkout",
  "QA-015": "Logged-in wallet UI",
  "QA-016": "Wallet-only pay",
  "QA-017": "Split pay",
  "QA-018": "Order payment total",
  "QA-019": "Card-only with balance",
  "QA-020": "Insufficient wallet + card",
  "QA-021": "Order detail split line",
  "QA-022": "Header wallet",
  "QA-023": "Account menu",
  "QA-024": "Guest checkout UX",
  "QA-025": "Wallet history UI",
  "QA-026": "GET /user/wallet",
  "QA-027": "GET /user/wallet/balance",
  "QA-028": "Ledger after checkout",
  "QA-029": "Ledger after cancel/refund",
  "QA-030": "Admin top-up visible",
  "QA-031": "Legacy B2B credit migration",
  "QA-032": "GET /user/b2b-account/ledger",
  "QA-033": "API cancel split refund",
  "QA-034": "API wallet-only cancel",
  "QA-035": "Cancel whole order (buyer)",
  "QA-036": "Cancel single line (buyer)",
  "QA-037": "Cancel last line (buyer)",
  "QA-038": "Sequential line cancels",
  "QA-039": "Order detail refund UI",
  "QA-040": "Refund hints (shipped)",
  "QA-041": "Partial refund (admin/core)",
  "QA-042": "Second partial refund",
  "QA-043": "Card-only refund",
  "QA-044": "Refund idempotency",
  "QA-045": "Failed refund retry",
  "QA-046": "Tax cert upload",
  "QA-047": "Tax exempt checkout",
  "QA-048": "Admin approve cert",
  "QA-049": "Admin reject cert",
  "QA-050": "Pending cert",
  "QA-051": "No cert",
  "QA-052": "County / jurisdiction",
  "QA-053": "EXEMPT does not block pay",
  "QA-054": "Cert file download",
  "QA-055": "Wrong state cert",
  "QA-056": "Missing ship-from",
  "QA-057": "Shipping quote errors",
  "QA-058": "Multi-seller cart",
  "QA-059": "Change county after tax calc",
  "QA-060": "Guest vs logged-in checkout",
  "QA-061": "No org credit at checkout",
  "QA-062": "Register business",
  "QA-063": "B2B wholesale pricing",
  "QA-064": "Wholesale ≠ tax exempt",
  "QA-065": "Team page copy",
  "QA-066": "B2B member checkout",
  "QA-067": "Invite member",
  "QA-068": "Remove member",
  "QA-069": "Personal buyer",
  "QA-070": "Tax vs B2B at pay",
  "QA-071": "No legacy b2b-credits URL",
  "QA-072": "Prefs page loads",
  "QA-073": "Defaults match catalog",
  "QA-074": "Enable push on device",
  "QA-075": "Admin My alerts filter",
  "QA-076": "Admin enable ODB alerts",
  "QA-077": "Seller contact email",
  "QA-078": "Empty My alerts OK",
  "QA-079": "Email off blocks mail [Web → Email]",
  "QA-080": "Email on restores mail [Web → Email]",
  "QA-081": "Push off blocks push [Mobile → Push]",
  "QA-082": "Push on delivers [Mobile → Push]",
  "QA-083": "Prefs sync Web↔Mobile",
  "QA-084": "Marketing email opt-out",
  "QA-085": "SMS verify + toggle",
  "QA-086": "order_placed",
  "QA-087": "marketplace_order_new",
  "QA-088": "payment_succeeded",
  "QA-089": "order_processing",
  "QA-090": "order_shipped",
  "QA-091": "Partial ship email",
  "QA-092": "order_completed",
  "QA-093": "payment_failed",
  "QA-094": "payment_expired",
  "QA-095": "order_cancelled",
  "QA-096": "Partial cancel email",
  "QA-097": "refund_completed — split",
  "QA-098": "refund_completed — wallet-only",
  "QA-099": "refund_completed — card-only",
  "QA-100": "refund_requested",
  "QA-101": "refund_failed",
  "QA-102": "return_submitted",
  "QA-103": "return_approved / rejected / refunded",
  "QA-104": "return_expiring",
  "QA-105": "claim_opened",
  "QA-106": "claim_updated / claim_resolved",
  "QA-107": "seller_message / buyer_message",
  "QA-108": "question_asked / answered",
  "QA-109": "review_received",
  "QA-110": "Seller application received/approved/rejected",
  "QA-111": "seller_suspended / reactivated",
  "QA-112": "payout_released / held",
  "QA-113": "listing_status",
  "QA-114": "Channel noise absent",
  "QA-115": "Storefront metrics panel",
  "QA-116": "Suppression blocks send",
  "QA-117": "Bounce webhook",
  "QA-118": "Contact deliverability read",
  "QA-119": "account_created",
  "QA-120": "abandoned_cart",
  "QA-121": "price_drop / back_in_stock / promotion",
  "QA-122": "contact_form",
  "QA-123": "In-app list",
  "QA-124": "Push deep link",
  "QA-125": "Background vs foreground",
  "QA-126": "Prefs survive relaunch",
  "QA-127": "iOS + Android both",
  "QA-128": "Returns timeline",
  "QA-129": "Return refund",
  "QA-130": "Buyer protection claim refund [Web+Admin]",
  "QA-131": "Post-purchase messages",
  "QA-132": "Cancel line after partial ship",
  "QA-133": "Payment tender panel",
  "QA-134": "Refund breakdown admin",
  "QA-135": "Admin partial-cancel totals",
  "QA-136": "Admin batch cancel-items",
  "QA-137": "Order history",
  "QA-138": "Approve/reject tax cert",
  "QA-139": "Cancel unshipped",
  "QA-140": "Cancel shipped (admin)",
  "QA-141": "Refund cancelled order",
  "QA-142": "Order refunds queue",
  "QA-143": "Returns review",
  "QA-144": "Admin cancel refund mode",
  "QA-145": "Fund any buyer wallet",
  "QA-146": "Users list wallet column",
  "QA-147": "Fund owner wallet (B2B tab)",
  "QA-148": "Set wallet balance",
  "QA-149": "B2B list columns",
  "QA-150": "B2B detail ledger",
  "QA-151": "Create B2B account",
  "QA-152": "Marketing promo note",
  "QA-153": "Seller order view",
  "QA-154": "Seller fulfill / ship",
  "QA-155": "Seller return/refund",
  "QA-156": "Payment tender on seller view",
  "QA-157": "Mobile login & orders",
  "QA-158": "Mobile wallet checkout",
  "QA-159": "Mobile cancel order",
  "QA-160": "Mobile cancel line",
  "QA-161": "Mobile notifications E2E",
  "QA-162": "Mobile tax certs",
  "QA-163": "Mobile wallet history",
  "QA-164": "Mobile returns/claims",
  "QA-165": "Mobile B2B team",
  "QA-166": "Push credentials regression",
  "QA-167": "Proportional refund (core)",
  "QA-168": "Full refund split (core)",
  "QA-169": "Wallet-only refund (core)",
  "QA-170": "API cart parity",
  "QA-171": "Marketplace-core vs API cancel",
  "QA-172": "Buyer order GET enrichment",
  "QA-173": "1CA internal refund API",
  "QA-174": "Claim refund endpoint",
  "QA-175": "Marketplace refund bridge",
  "QA-176": "Split order from 1CA",
  "QA-177": "1CA vs ODB boundary",
  "QA-178": "1CA native B2B unchanged",
  "QA-179": "Order sync after refund",
  "QA-180": "Return flow in 1CA UI",
  "QA-181": "Fulfill cancel",
  "QA-182": "Branded line-item emails",
  "QA-183": "Search / fitment",
  "QA-184": "Sitemap",
  "QA-185": "Brand logos",
  "QA-186": "Cart persist on login",
  "QA-187": "Guest order lookup",
  "QA-188": "Multi-seller order admin",
};

test.describe("OneDirectBuy — Production QA (rule coverage)", () => {
  for (const id of PRODUCTION_QA_IDS) {
    test(`${id}: ${TITLES[id] || id}`, async ({ soft }) => {
      await soft(id, TITLES[id] || id, async () => {
        expect(() => assertProductionQa(id)).not.toThrow();
      });
    });
  }
});
